build_check:
- arch: aarch64
  board: 
  - name: raspi4
  - name: hi3093
  - name: kp920
- arch: arm
  board:
  - name: m4
- arch: x86_64
  board:
  - name: x86_64
- arch: riscv64
  board:
  - name: rv64virt
- arch: all
  board:
  - name: all

demo_check:
- arch: aarch64
  board: 
  - name: raspi4
  - name: hi3093
- arch: arm
  board:
  - name: m4
    app: 
    - app_name: helloworld
    - app_name: helloworld sim
    - app_name: shell 
    - app_name: fatfs 
  - name: rk3568_jailhouse
- arch: x86_64
  board:
  - name: x86_64
- arch: riscv64
  board:
  - name: riscv64virt
    app: 
    - app_name: hello_world
    - app_name: rhealstone-task-switch
    - app_name: rhealstone-task-preempt
    - app_name: rhealstone-message-latency
    - app_name: rhealstone-deadlock-break
    - app_name: rhealstone-semaphore-shuffle
