build_check:
- arch: aarch64
  board: 
  - name: raspi4
  - name: hi3093
- arch: arm
  board:
  - name: m4
- arch: x86_64
  board:
  - name: x86_64

demo_check:
- arch: aarch64
  board: 
  - name: raspi4
  - name: hi3093
- arch: arm
  board:
  - name: m4
    app: 
    - app_name: helloworld
    - app_name: helloworld sim
    - app_name: shell 
  - name: rk3568_jailhouse
- arch: x86_64
  board:
  - name: x86_64